/*
 FireShot - Webpage Screenshots and Annotations
 Copyright (C) 2007-2021 Evgeny Suslikov (evgeny@suslikov.ru)
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";
var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,e){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,e):$jscomp.polyfillUnisolated(a,b,c,e))};
$jscomp.polyfillUnisolated=function(a,b,c,e){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var h=a[e];if(!(h in c))return;c=c[h]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,e){var h=a.split(".");a=1===h.length;e=h[0];e=!a&&e in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<h.length-1;f++){var d=h[f];if(!(d in e))return;e=e[d]}h=h[h.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?e[h]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,h,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[h]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(h):$jscomp.POLYFILL_PREFIX+h,h=
$jscomp.propertyToPolyfillSymbol[h],$jscomp.defineProperty(e,h,{configurable:!0,writable:!0,value:b})))};
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(d){return d instanceof h?d:new h(function(k,g){k(d)})}if(a&&(!($jscomp.FORCE_POLYFILL_PROMISE||$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION&&"undefined"===typeof $jscomp.global.PromiseRejectionEvent)||!$jscomp.global.Promise||-1===$jscomp.global.Promise.toString().indexOf("[native code]")))return a;b.prototype.asyncExecute=function(d){if(null==this.batch_){this.batch_=[];var k=this;this.asyncExecuteFunction(function(){k.executeBatch_()})}this.batch_.push(d)};
var e=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(d){e(d,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var d=this.batch_;this.batch_=[];for(var k=0;k<d.length;++k){var g=d[k];d[k]=null;try{g()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(d){this.asyncExecuteFunction(function(){throw d;})};var h=function(d){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];this.isRejectionHandled_=!1;var k=this.createResolveAndReject_();
try{d(k.resolve,k.reject)}catch(g){k.reject(g)}};h.prototype.createResolveAndReject_=function(){function d(l){return function(m){g||(g=!0,l.call(k,m))}}var k=this,g=!1;return{resolve:d(this.resolveTo_),reject:d(this.reject_)}};h.prototype.resolveTo_=function(d){if(d===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(d instanceof h)this.settleSameAsPromise_(d);else{a:switch(typeof d){case "object":var k=null!=d;break a;case "function":k=!0;break a;default:k=!1}k?this.resolveToNonPromiseObj_(d):
this.fulfill_(d)}};h.prototype.resolveToNonPromiseObj_=function(d){var k=void 0;try{k=d.then}catch(g){this.reject_(g);return}"function"==typeof k?this.settleSameAsThenable_(k,d):this.fulfill_(d)};h.prototype.reject_=function(d){this.settle_(2,d)};h.prototype.fulfill_=function(d){this.settle_(1,d)};h.prototype.settle_=function(d,k){if(0!=this.state_)throw Error("Cannot settle("+d+", "+k+"): Promise already settled in state"+this.state_);this.state_=d;this.result_=k;2===this.state_&&this.scheduleUnhandledRejectionCheck_();
this.executeOnSettledCallbacks_()};h.prototype.scheduleUnhandledRejectionCheck_=function(){var d=this;e(function(){if(d.notifyUnhandledRejection_()){var k=$jscomp.global.console;"undefined"!==typeof k&&k.error(d.result_)}},1)};h.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var d=$jscomp.global.CustomEvent,k=$jscomp.global.Event,g=$jscomp.global.dispatchEvent;if("undefined"===typeof g)return!0;"function"===typeof d?d=new d("unhandledrejection",{cancelable:!0}):
"function"===typeof k?d=new k("unhandledrejection",{cancelable:!0}):(d=$jscomp.global.document.createEvent("CustomEvent"),d.initCustomEvent("unhandledrejection",!1,!0,d));d.promise=this;d.reason=this.result_;return g(d)};h.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var d=0;d<this.onSettledCallbacks_.length;++d)f.asyncExecute(this.onSettledCallbacks_[d]);this.onSettledCallbacks_=null}};var f=new b;h.prototype.settleSameAsPromise_=function(d){var k=this.createResolveAndReject_();
d.callWhenSettled_(k.resolve,k.reject)};h.prototype.settleSameAsThenable_=function(d,k){var g=this.createResolveAndReject_();try{d.call(k,g.resolve,g.reject)}catch(l){g.reject(l)}};h.prototype.then=function(d,k){function g(n,p){return"function"==typeof n?function(r){try{l(n(r))}catch(t){m(t)}}:p}var l,m,q=new h(function(n,p){l=n;m=p});this.callWhenSettled_(g(d,l),g(k,m));return q};h.prototype.catch=function(d){return this.then(void 0,d)};h.prototype.callWhenSettled_=function(d,k){function g(){switch(l.state_){case 1:d(l.result_);
break;case 2:k(l.result_);break;default:throw Error("Unexpected state: "+l.state_);}}var l=this;null==this.onSettledCallbacks_?f.asyncExecute(g):this.onSettledCallbacks_.push(g);this.isRejectionHandled_=!0};h.resolve=c;h.reject=function(d){return new h(function(k,g){g(d)})};h.race=function(d){return new h(function(k,g){for(var l=$jscomp.makeIterator(d),m=l.next();!m.done;m=l.next())c(m.value).callWhenSettled_(k,g)})};h.all=function(d){var k=$jscomp.makeIterator(d),g=k.next();return g.done?c([]):new h(function(l,
m){function q(r){return function(t){n[r]=t;p--;0==p&&l(n)}}var n=[],p=0;do n.push(void 0),p++,c(g.value).callWhenSettled_(q(n.length-1),m),g=k.next();while(!g.done)})};return h},"es6","es3");
var currentTab,currentFrameId,imgData=[],extVersion="0.0",extVersionFull="0.0",savedCapParamsForDebugging,updateURL="",pendingCapFunction,capCallbackCompleted,executeScriptTO,capId=0,processedId=0,guiItemsLocked=!1,resumeMenuEnabled=!1,shortcutProcessing=!1,commPortName="FireShot Comm Port #"+Math.ceil(45309714203*Math.random()),capResult,capLinks,multiPDFMode,canBeBetter,advFeaturesChecked=!1,tabURL,tabTitle,fPermissionsPageOpened=!1,fForcedPro=!1,fForceRegistered=!1,fSilentMode=!1,pendingResponse,
pendingGMailJSON,fInjectGmailScript=!1,fCapturing=!1,fAbortCapturing=!1,fnCancelSelection;function enableHotkey(a){a?setTimeout(function(){shortcutProcessing=!1},500):shortcutProcessing=!0}
function getVersionInfo(){""==getOption(cGUID,"")&&setOption(cGUID,getUUIDv4());var a=new XMLHttpRequest;a.open("GET",chrome.extension.getURL("manifest.json"),!0);a.onreadystatechange=function(){this.readyState==XMLHttpRequest.DONE&&(extVersion=JSON.parse(this.responseText).version.split(".",3).join("."),extVersionFull=JSON.parse(this.responseText).version.split(".",4).join("."),updateURL=JSON.parse(this.responseText).update_url,fSilentMode="hpbicldbpgipcloiojdbchegbbjiobbm"==extensionId||"adpnodbfhlagloahhdhjggicnfcpggkm"==
extensionId,isWindows()&&!isOnlyLite()?fsNativePlugin.init(function(){getConsolePtr()("Callback from fsNative");displayAnnouncements();switchToProIfRequired();updateContextMenu()}.bind(this)):displayAnnouncements())};a.send()}
function displayAnnouncements(){if("true"===getOption(cFirstTimeRun,"true"))setOption(cFirstTimeRun,!1),setOption(cCurrentVersion,extVersion),fSilentMode||openURL(getInstalledPageURL());else{var a=getOption(cCurrentVersion,"0.0");extVersion!=a&&(isNativeSupported()||fSilentMode||showBadge("https://getfireshot.com/updated-lite.php?app="+getBrowserId()+"&ver="+extVersion))}}
function getInstalledPageURL(){var a="&app="+getBrowserId();return isNativeSupported()?"https://getfireshot.com/installed.php?ver="+extVersion+a+"&native=1":"https://getfireshot.com/installed-lite.php?ver="+extVersion+a}
function nativeHostUpdated(a){getConsolePtr()("Native module has updated to the "+a+" version.");gaTrack("UA-1025658-9","fireshot.com","NativeHostUpdated");getOption(cCurrentVersion,"0.0")==extVersion||a!=extVersionFull||fSilentMode||showBadge("https://getfireshot.com/updated.php?app="+getBrowserId()+"&ver="+a+"&h="+(isProMode()?"1":"0"))}
function switchToProIfRequired(){fForcedPro=isCustomBuild()||"{5e11ab1e-083c-11e5-a6c0-1697f925ec7b}"==extensionId;fForceRegistered=isCustomBuild();setOption(cPluginProModePref,"true"===getOption(cPluginProModePref)||fForcedPro);setOption(cRegisteredPref,"true"===getOption(cRegisteredPref)||fForceRegistered)}
function pluginEvent(a){var b=a.topic,c=a.data?a.data+"":"";"status"==b?a.code==statusHostReady?pluginCommand("setAddonVersion",{version:extVersionFull,browser:extensionBrowser,id:extensionId,guid:getOption(cGUID)}):(gaTrack("UA-1025658-9","fireshot.com","NativeError-"+a.data),alert("FireShot failed to update. The updater reported the following error: \r\n-----------------------------------------------\r\n"+a.data+"\r\n-----------------------------------------------\r\n\r\nFireShot will have to work in Lite mode."),
getConsolePtr()("Error from native module: "+a.data)):"openURL"==b?openURL(c):"enableResumeMenu"==b?(getConsolePtr()("enableResumeMenu "+c),resumeMenuEnabled="enable"==c,setTimeout(function(){updateContextMenu()},10)):"setupMode"==b?(setOption(cPluginProModePref,fForcedPro||"false"!=c),updateContextMenu()):"setRegistered"==b?(setOption(cRegisteredPref,fForceRegistered||"false"!=c),updateContextMenu()):"getInfo"==b?getInfo(c,function(e){pluginCommand("processInfo",{data:e})}):"sendCrashReport"==b?
sendCrashReport(c):"base64Content"==b&&pendingResponse?pendingResponse(c):"sendToGmail"==b?openInGmail(c):"switchToLite"==b?switchToLiteMode():"getUSPTOData"==b&&doUSPTORequest(c)}function openInGmail(a){pendingGMailJSON=a;chrome.permissions.contains({origins:["https://mail.google.com/*"]},function(b){b?openGmailComposer():openGmailPermissionsPage()})}
function lockItems(){guiItemsLocked=!0;chrome.contextMenus.removeAll();chrome.browserAction.setTitle({title:"FireShot Editor is currently displayed.\r\nPlease close it to take the next capture.\r\n\r\n(switching to FireShot Pro also helps!)"});chrome.browserAction.setPopup({popup:""})}function unlockItems(){guiItemsLocked=!1;setTimeout(function(){updateContextMenu()},10);chrome.browserAction.setTitle({title:"FireShot - Capture page"});chrome.browserAction.setPopup({popup:"fsPopup.html"})}
function checkTabReadyForCapturing(a,b,c){var e=setTimeout(function(){e&&(e=void 0,c(!1))},b);chrome.tabs.executeScript(a,{code:"{}",runAt:"document_start"},function(){var h=!chrome.runtime.lastError;e&&(clearTimeout(e),e=void 0,c(h))})}
function initMessaging(){try{chrome.runtime.onMessage.addListener(function(a,b,c){switch(a.message){case "getPortName":c({portName:commPortName});break;case "loadScript":getConsolePtr()("execScript event");void 0!==executeScriptTO&&(clearTimeout(executeScriptTO),executeScriptTO=void 0);var e=b.frameId,h=["scripts/fsXBrowserSupport.js","scripts/fsUtils.js","scripts/fsSelection.js","scripts/fsLinks.js","scripts/fsContent.js"],f=0,d=function(){f<h.length?(getConsolePtr()("Executing "+h[f]),chrome.tabs.executeScript(currentTab.id,
fixObjectForOldChrome({file:h[f++],runAt:"document_start",frameId:e}),d)):setTimeout(pendingCapFunction,200)};d();break;case "execScript":getConsolePtr()("execScript event");void 0!==executeScriptTO&&(clearTimeout(executeScriptTO),executeScriptTO=void 0);setTimeout(function(){return pendingCapFunction(!1)},100);break;case "checkFSAvailabilityEvt":return getConsolePtr()("checkFSAvailabilityEvt"),c({FSAvailable:!0,FSNative:isNativeSupported(),FSUpgraded:"true"===getOption(cPluginProModePref),FSVersion:extVersionFull}),
!0;case "capturePageEvt":var k=parseInt(a.Action);k==cActionUpgrade?isNativeSupported()?doUpgrade():openURL("https://getfireshot.com/buy.php?SRC="+getBrowserId()+"-lite"):executeGrabber(k===cActionSilentSave?cActionSilentAdd:k,"true"==a.Entire?cModeEntire:cModeVisible,a.Data,function(){k===cActionSilentSave&&pluginCommand("storeEncodedContent",{path:a.Data});k!==cActionBASE64Content&&pendingResponse&&pendingResponse("")},!0,b.frameId);break;case "getScreenshotsForGmail":return pendingGMailJSON?(c(pendingGMailJSON),
pendingGMailJSON=void 0,!0):!1;case "switchToNativeEvt":installNative();break;case "activateFireShot":getConsolePtr()(a.name+" "+a.key),c("OK"),pluginCommand("activateFireShot",{name:a.name,key:a.key})}})}catch(a){}}function checkBadgeAction(){return getOption(cQueuedBadgeURLPref)&&"undefined"!==getOption(cQueuedBadgeURLPref)?(openURL(getOption(cQueuedBadgeURLPref)),showBadge(void 0),setOption(cFirstTimeRun,!1),setOption(cCurrentVersion,extVersion),!0):!1}
function checkActivationPage(a){chrome.tabs.query({currentWindow:!0,active:!0},function(b){try{if(0!==b.length&&b[0].url){var c=b[0];/https:\/\/getfireshot(\.com)?\/activate\.php/.test(c.url)&&(a(!0),chrome.tabs.executeScript(c.id,{file:"scripts/fsActivation.js",runAt:"document_start"},function(){""!==chrome.runtime.lastError&&(chrome.runtime.lastError="")}))}else a(!1)}catch(e){a(!1)}})}
function getMenuSettings(a){function b(c){var e="capturing-prohibited"===c,h="extension-page"===c,f="file-not-allowed"===c,d="capturing-executescript-disabled"===c;c=!isNativeSupported();var k="true"===getOption(cPluginProModePref),g="true"===getOption(cRegisteredPref),l=getLastMode();d={sepMain1:"visible",sepMain2:"visible",mnuFeaturesUnavailable:e?"visible":"hidden",mnuEnableFileSupport:f?"visible":"hidden",mnuPrivateBrowsingWarning:"hidden",mnuQuickLaunch:e&&(l==cModeEntire||l==cModeSelected||
l==cModeVisible)||d&&(l==cModeEntire||l==cModeSelected)?"disabled":"enabled",mnuCaptureVisible:e?"disabled":"visible",mnuCaptureEntire:e||d?"disabled":"visible",mnuCaptureSelection:e||d?"disabled":"visible",mnuCaptureVisibleLite:e?"disabled":"visible",mnuCaptureEntireLite:e||d?"disabled":"visible",mnuCaptureSelectionLite:e||d?"disabled":"visible",mnuPreferencesLite:c?"visible":"hidden",mnuViewDemo:c?"hidden":"visible",mnuSupport:c?"hidden":"visible",mnuAbout:c?"hidden":"visible",sepEditor:c?"hidden":
"visible",sepSupport1:c?"hidden":"visible",sepSupport2:c?"hidden":"visible",sepAdvanced:isWindows()?"visible":"hidden",mnuMiscellaneousFolder:c?"hidden":"visible",mnuResume:c?"hidden":resumeMenuEnabled?"enabled":"disabled",mnuUpgrade:c?"hidden":k?"hidden":"visible",mnuRegister:c?"hidden":k&&!g?"visible":"hidden",mnuEnterLicense:c?"hidden":k&&!g?"visible":"hidden",mnuOpenFile:c?"hidden":k?"enabled":"disabled",mnuOpenClipboard:c?"hidden":k?"enabled":"disabled",mnuLicenseInfo:c?"hidden":k&&g?"visible":
"hidden",divCaptureToolsLite:c?"visible":"hidden",divCaptureTools:c?"hidden":"visible",mnuFireShotNative:isWindows()&&c?"visible":"hidden",mnuStopFireShot:"hidden"};for(var m in d)fCapturing?d[m]="mnuStopFireShot"===m?"visible":"hidden":e?d[m]="mnuFeaturesUnavailable"===m?"visible":"hidden":h?"mnuPreferencesLite"===m||"mnuFireShotNative"===m&&isWindows()&&c?d[m]="visible":d[m]="hidden":f&&(d[m]="mnuEnableFileSupport"===m?"visible":"hidden");a(d)}chrome.tabs.query({currentWindow:!0,active:!0},function(c){try{if(0!==
c.length&&c[0].url){var e=c[0];/^chrome-extension.*/.test(e.url)?b("capturing-executescript-disabled"):/^safari-web-extension.*/.test(e.url)?b("extension-page"):/^file:\/\/.*/.test(e.url)?chrome.extension.isAllowedFileSchemeAccess(function(h){h?b("capturing-allowed"):b("file-not-allowed")}):/^(http|https|ftp|ftps):\/\/.*/.test(e.url)&&!/^https?:\/\/chrome.google.com\/.*$/.test(e.url)?b("capturing-allowed"):b("capturing-executescript-disabled")}else b("capturing-prohibited")}catch(h){b("capturing-prohibited")}})}
function capturePage(a,b,c,e,h,f){void 0!==executeScriptTO&&(clearTimeout(executeScriptTO),executeScriptTO=void 0);capId++;currentTab=h;currentFrameId=f;capCallbackCompleted=e;pendingCapFunction=function(d){d?captureVisibleTabPlain(a,c,e):doCapturing(a,b,c,e)};getConsolePtr()("capturePage: checking capabilities at "+h.url+". Tab state is: "+h.status);b==cModeBrowser&&void 0!==h.url&&void 0!==h.title?setTimeout(function(){getConsolePtr()("Calling captureBrowser directly...");enableHotkey(!1);lockItems();
pluginCommand("captureBrowser",{action:a+":-",url:h.url,title:h.title});unlockItems();enableHotkey(!0);capCallbackCompleted&&capCallbackCompleted()},100):(executeScriptTO=setTimeout(function(){getConsolePtr()("Calling doCapturing on timeout");pendingCapFunction(!0)},1E3),chrome.tabs.executeScript(h.id,fixObjectForOldChrome({file:"scripts/fsScriptChecker.js",runAt:"document_start",frameId:f}),function(){chrome.runtime.lastError&&(clearTimeout(executeScriptTO),executeScriptTO=void 0,getConsolePtr()("Calling doCapturing on lastError"),
pendingCapFunction(!0))}))}function getActionLocaleId(a){switch(a){case cActionSave:return"action_save";case cActionSavePDF:return"action_save_pdf";case cActionClipboard:return"action_copy";case cActionEMail:return"action_email";case cActionPaint:return"action_external";case cActionSendOneNote:return"action_onenote";case cActionUpload:return"action_upload";case cActionPrint:return"action_print";case cActionMultiPDF:return"action_save_pdf_single";default:return"action_edit"}}
function getLADescription(){var a=getActionLocaleId(getLastAction()),b=!isNativeSupported();switch(getLastMode()){case cModeVisible:var c=b?"action_capture_visible_lite":"action_capture_visible";break;case cModeSelected:c=b?"action_capture_selection_lite":"action_capture_selection";break;case cModeBrowser:c="action_capture_browser";break;case cModeTabs:c="action_capture_tabs";break;default:c=b?"action_capture_entire_lite":"action_capture_entire"}return b?chrome.i18n.getMessage(c):chrome.i18n.getMessage(c)+
" "+chrome.i18n.getMessage(a)}function stopCapturing(){fAbortCapturing=!0;getConsolePtr()("Capturing canceled");fnCancelSelection&&fnCancelSelection()}
function captureVisibleTabPlain(a,b,c){chrome.tabs.captureVisibleTab(void 0,{format:"png"},function(e){if(!chrome.runtime.lastError&&e){var h=new Image;h.onload=function(){pluginCommand("captureInit");pluginCommand("captureTabPNG",{dataurl:e,datasize:e.length,x:0,y:0});tabURL=currentTab.url;tabTitle=currentTab.title;var f={action:a,url:tabURL,title:tabTitle,left:0,top:0,width:h.width,height:h.height};f.browserVersion=parseInt(navigator.userAgent.match(/(Chrom(e|ium)|Safari)\/([0-9]+)\./)[3]);f.usrData=
b;pendingResponse=function(d){pendingResponse=void 0;port.postMessage({topic:"sendFireShotCaptureCompleteEvent",data:d})};lockItems();pluginCommand("captureDone",f);enableHotkey(!0);unlockItems();c&&c(!0)};h.src=e}})}
function doCapturing(a,b,c,e){function h(g){chrome.tabs.captureVisibleTab(currentTab.windowId,{format:"jpeg"},function(l){var m=-1,q=-1;if(chrome.runtime.lastError)console.error(chrome.runtime.lastError.message);else try{var n=getJpegExtents(l);m=n[0];q=n[1];getConsolePtr()("Emulation extents: "+n[0]+" x "+n[1])}catch(p){getConsolePtr()(p.toString())}g(m,q)})}fAbortCapturing=!1;getConsolePtr()("doCapturing");if(capId<=processedId++)capId=processedId;else try{var f=chrome.tabs.connect(currentTab.id,
{name:commPortName,frameId:currentFrameId}),d=!0,k=function(){d&&(fCapturing=!1,updateContextMenu(),e&&e(!1))};f.onMessage.addListener(function(g){getConsolePtr()(JSON.stringify(g));switch(g.topic){case "initAborted":getConsolePtr()("init Aborted");fCapturing=!1;updateContextMenu();e&&e();break;case "initDone":tabURL=g.url;tabTitle=g.title;d=!1;enableHotkey(!1);switch(b){case cModeVisible:case cModeEntire:h(function(l,m){l=closestToInt(l/g.cw);m=closestToInt(m/g.ch);pluginCommand("captureInit");f.postMessage({topic:"setRatio",
ratioW:l,ratioH:m});f.postMessage({topic:"scrollNext"})});break;case cModeSelected:h(function(l,m){l=closestToInt(l/g.cw);m=closestToInt(m/g.ch);pluginCommand("captureInit");fnCancelSelection=function(){f.postMessage({topic:"cancelSelection"})};f.postMessage({topic:"setRatio",ratioW:l,ratioH:m});f.postMessage({topic:"selectArea"})});break;case cModeBrowser:enableHotkey(!1),lockItems(),pluginCommand("captureBrowser",{action:a+":-",url:tabURL,title:tabTitle}),unlockItems(),enableHotkey(!0)}break;case "areaSelected":fnCancelSelection=
void 0;f.postMessage({topic:"scrollNext"});break;case "areaSelectionCanceled":fnCancelSelection=void 0;fCapturing=!1;updateContextMenu();enableHotkey(!0);f.onMessage.removeListener(arguments.callee);f.onDisconnect.removeListener(k);break;case "scrollDone":chrome.tabs.captureVisibleTab(currentTab.windowId,{format:"png"},function(l){chrome.runtime.lastError||pluginCommand("captureTabPNG",{dataurl:l,datasize:l.length,x:g.x,y:g.y});f.postMessage({topic:"scrollNext",cancel:fAbortCapturing})});break;case "scrollFinished":getConsolePtr()("FINISHED ("+
g.rows+" x "+g.cols+")");savedCapParamsForDebugging={action:g.action,left:g.left,top:g.top,width:g.width,height:g.height,rows:g.rows,cols:g.cols,cw:g.cw,ch:g.ch,ratioW:g.ratioW,ratioH:g.ratioH,cropLeft:g.cropLeft,cropRight:g.cropRight,cropTop:g.cropTop,cropBottom:g.cropBottom};g.url=tabURL;g.title=tabTitle;g.key="-";g.action=a;g.browserVersion=parseInt(navigator.userAgent.match(/(Chrom(e|ium)|Safari)\/([0-9]+)\./)[3]);g.usrData=c;pendingResponse=function(l){pendingResponse=void 0;f.postMessage({topic:"sendFireShotCaptureCompleteEvent",
data:l})};fCapturing=!1;lockItems();pluginCommand("captureDone",g);enableHotkey(!0);unlockItems();f.onMessage.removeListener(arguments.callee);f.onDisconnect.removeListener(k);e&&e(!0);break;case "setOption":setOption(g.optionName,g.optionValue)}});f.onDisconnect.addListener(k);fCapturing=!0;updateContextMenu();f.postMessage({topic:"init",mode:b,debug:isDebug,options:JSON.stringify(localStorage),p:"true"===getOption(cPluginProModePref),native:isNativeSupported(),frameMode:0<currentFrameId})}catch(g){fCapturing=
!1,e&&e(!1)}}
function genericOnClick(a,b){switch(a.menuItemId){case mnuTest:doTest();break;case mnuStopFireShot:stopCapturing();break;case mnuVisibleEdit:executeGrabber(cActionEdit,cModeVisible);break;case mnuVisibleSave:executeGrabber(cActionSave,cModeVisible);break;case mnuVisibleSavePDF:executeGrabber(cActionSavePDF,cModeVisible);break;case mnuVisibleSendOneNote:executeGrabber(cActionSendOneNote,cModeVisible);break;case mnuVisibleUpload:executeGrabber(cActionUpload,cModeVisible);break;case mnuVisiblePrint:executeGrabber(cActionPrint,cModeVisible);
break;case mnuVisibleCopy:executeGrabber(cActionClipboard,cModeVisible);break;case mnuVisibleEMail:executeGrabber(cActionEMail,cModeVisible);break;case mnuVisibleExtEditor:executeGrabber(cActionPaint,cModeVisible);break;case mnuEntireEdit:executeGrabber(cActionEdit,cModeEntire);break;case mnuEntireSave:executeGrabber(cActionSave,cModeEntire);break;case mnuEntireSavePDF:executeGrabber(cActionSavePDF,cModeEntire);break;case mnuEntireSendOneNote:executeGrabber(cActionSendOneNote,cModeEntire);break;case mnuEntireUpload:executeGrabber(cActionUpload,
cModeEntire);break;case mnuEntirePrint:executeGrabber(cActionPrint,cModeEntire);break;case mnuEntireCopy:executeGrabber(cActionClipboard,cModeEntire);break;case mnuEntireEMail:executeGrabber(cActionEMail,cModeEntire);break;case mnuEntireExtEditor:executeGrabber(cActionPaint,cModeEntire);break;case mnuSelectedEdit:executeGrabber(cActionEdit,cModeSelected);break;case mnuSelectedSave:executeGrabber(cActionSave,cModeSelected);break;case mnuSelectedSavePDF:executeGrabber(cActionSavePDF,cModeSelected);
break;case mnuSelectedSendOneNote:executeGrabber(cActionSendOneNote,cModeSelected);break;case mnuSelectedUpload:executeGrabber(cActionUpload,cModeSelected);break;case mnuSelectedPrint:executeGrabber(cActionPrint,cModeSelected);break;case mnuSelectedCopy:executeGrabber(cActionClipboard,cModeSelected);break;case mnuSelectedEMail:executeGrabber(cActionEMail,cModeSelected);break;case mnuSelectedExtEditor:executeGrabber(cActionPaint,cModeSelected);break;case mnuBrowserEdit:executeGrabber(cActionEdit,cModeBrowser);
break;case mnuBrowserSave:executeGrabber(cActionSave,cModeBrowser);break;case mnuBrowserSavePDF:executeGrabber(cActionSavePDF,cModeBrowser);break;case mnuBrowserSendOneNote:executeGrabber(cActionSendOneNote,cModeBrowser);break;case mnuBrowserUpload:executeGrabber(cActionUpload,cModeBrowser);break;case mnuBrowserPrint:executeGrabber(cActionPrint,cModeBrowser);break;case mnuBrowserCopy:executeGrabber(cActionClipboard,cModeBrowser);break;case mnuBrowserEMail:executeGrabber(cActionEMail,cModeBrowser);
break;case mnuBrowserExtEditor:executeGrabber(cActionPaint,cModeBrowser);break;case mnuAllTabsEdit:tabsPermissionRequired(function(){executeGrabber(cActionEdit,cModeTabs)});break;case mnuAllTabsSinglePDF:tabsPermissionRequired(function(){executeGrabber(cActionMultiPDF,cModeTabs)});break;case mnuAllTabsSave:tabsPermissionRequired(function(){executeGrabber(cActionSave,cModeTabs)});break;case mnuAllTabsSendOneNote:tabsPermissionRequired(function(){executeGrabber(cActionSendOneNote,cModeTabs)});break;
case mnuAllTabsUpload:tabsPermissionRequired(function(){executeGrabber(cActionUpload,cModeTabs)});break;case mnuAllTabsPrint:tabsPermissionRequired(function(){executeGrabber(cActionPrint,cModeTabs)});break;case mnuAllTabsClipboard:tabsPermissionRequired(function(){executeGrabber(cActionClipboard,cModeTabs)});break;case mnuAllTabsEMail:tabsPermissionRequired(function(){executeGrabber(cActionEMail,cModeTabs)});break;case mnuAllTabsExtEditor:tabsPermissionRequired(function(){executeGrabber(cActionPaint,
cModeTabs)});break;case mnuLastAction:captureLastUsedMode();break;case mnuPreferences:openExtensionPreferences();break;case mnuViewDemo:openDemoPage();break;case mnuSupport:openSupportPage();break;case mnuAPI:openAPIPage();break;case mnuUnlockProFeatures:case mnuUpgrade:doUpgrade();break;case mnuRegister:doRegister();break;case mnuEnterLicense:enterLicense();break;case mnuOpenFile:openFile();break;case mnuOpenClipboard:openClipboard();break;case mnuResume:resumeEditing();break;case mnuFireShotNative:installNative();
break;case mnuLicensingInfo:showLicenseInfo();break;case mnuAbout:showAbout()}}function updateLastActionInContextMenu(){chrome.commands.getAll(function(a){getLAShortcut(function(b){chrome.contextMenus.update(mnuLastAction,{onclick:genericOnClick,title:getLADescription()+"    "+b},function(){""!==chrome.runtime.lastError&&(chrome.runtime.lastError="")})})})}
var fEntered=!1,mnuStopFireShot,mnuLastAction,mnuVisibleEdit,mnuVisibleSave,mnuVisibleSavePDF,mnuVisibleSendOneNote,mnuVisibleUpload,mnuVisiblePrint,mnuVisibleCopy,mnuVisibleEMail,mnuVisibleExtEditor,mnuEntireEdit,mnuEntireSave,mnuEntireSavePDF,mnuEntireSendOneNote,mnuEntireUpload,mnuEntirePrint,mnuEntireCopy,mnuEntireEMail,mnuEntireExtEditor,mnuSelectedEdit,mnuSelectedSave,mnuSelectedSavePDF,mnuSelectedSendOneNote,mnuSelectedUpload,mnuSelectedPrint,mnuSelectedCopy,mnuSelectedEMail,mnuSelectedExtEditor,
mnuBrowserEdit,mnuBrowserSave,mnuBrowserSavePDF,mnuBrowserSendOneNote,mnuBrowserUpload,mnuBrowserPrint,mnuBrowserCopy,mnuBrowserEMail,mnuBrowserExtEditor,mnuResume,mnuOpenFile,mnuOpenClipboard,mnuPreferences,mnuRegister,mnuEnterLicense,mnuUpgrade,mnuViewDemo,mnuSupport,mnuAPI,mnuLicensingInfo,mnuAbout,mnuFireShotNative,mnuTest,mnuAllTabsEdit,mnuAllTabsSinglePDF,mnuUnlockProFeatures,mnuAllTabsSave,mnuAllTabsSendOneNote,mnuAllTabsUpload,mnuAllTabsPrint,mnuAllTabsEMail,mnuAllTabsExtEditor,mnuAllTabsClipboard;
function updateContextMenu(){fEntered||(fEntered=!0,chrome.contextMenus.removeAll(function(){function a(){chrome.contextMenus.create({onclick:function(){},type:"separator",documentUrlPatterns:h})}if("true"!==getOption(cContextMenuIntegrationPref,"true"))fEntered=!1;else{var b="true"===getOption(cPluginProModePref),c="true"===getOption(cRegisteredPref),e=!isNativeSupported(),h=["http://*/*","https://*/*","ftp://*/*","file://*/*"];if(fCapturing)mnuStopFireShot=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_capture_stop"),
onclick:genericOnClick}),fEntered=!1;else if(!guiItemsLocked){isDebug&&(mnuTest=chrome.contextMenus.create({title:"do test",onclick:genericOnClick}),a());mnuLastAction=chrome.contextMenus.create({title:"Last action",onclick:genericOnClick,documentUrlPatterns:h});if(!isSafari()){a();if(e)mnuEntireEdit=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_capture_entire_lite")+"...",onclick:genericOnClick,documentUrlPatterns:h}),mnuVisibleEdit=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_capture_visible_lite")+
"...",onclick:genericOnClick,documentUrlPatterns:h}),mnuSelectedEdit=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_capture_selection_lite")+"...",onclick:genericOnClick,documentUrlPatterns:h}),a();else{var f=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_capture_visible")+"..."});mnuVisibleEdit=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_edit")+"...",parentId:f,onclick:genericOnClick});mnuVisibleSave=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_save")+
"...",parentId:f,onclick:genericOnClick});mnuVisibleSavePDF=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_save_pdf")+"...",parentId:f,onclick:genericOnClick});mnuVisibleSendOneNote=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_onenote")+"...",parentId:f,onclick:genericOnClick});mnuVisibleUpload=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_upload")+"...",parentId:f,onclick:genericOnClick});mnuVisiblePrint=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_print")+
"...",parentId:f,onclick:genericOnClick});mnuVisibleCopy=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_copy")+"...",parentId:f,onclick:genericOnClick});mnuVisibleEMail=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_email")+"...",parentId:f,onclick:genericOnClick});mnuVisibleExtEditor=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_external")+"...",parentId:f,onclick:genericOnClick});f=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_capture_entire")+
"..."});mnuEntireEdit=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_edit")+"...",parentId:f,onclick:genericOnClick});mnuEntireSave=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_save")+"...",parentId:f,onclick:genericOnClick});mnuEntireSavePDF=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_save_pdf")+"...",parentId:f,onclick:genericOnClick});mnuEntireSendOneNote=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_onenote")+"...",
parentId:f,onclick:genericOnClick});mnuEntireUpload=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_upload")+"...",parentId:f,onclick:genericOnClick});mnuEntirePrint=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_print")+"...",parentId:f,onclick:genericOnClick});mnuEntireCopy=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_copy")+"...",parentId:f,onclick:genericOnClick});mnuEntireEMail=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_email")+
"...",parentId:f,onclick:genericOnClick});mnuEntireExtEditor=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_external")+"...",parentId:f,onclick:genericOnClick});f=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_capture_selection")+"..."});mnuSelectedEdit=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_edit")+"...",parentId:f,onclick:genericOnClick});mnuSelectedSave=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_save")+"...",parentId:f,
onclick:genericOnClick});mnuSelectedSavePDF=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_save_pdf")+"...",parentId:f,onclick:genericOnClick});mnuSelectedSendOneNote=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_onenote")+"...",parentId:f,onclick:genericOnClick});mnuSelectedUpload=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_upload")+"...",parentId:f,onclick:genericOnClick});mnuSelectedPrint=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_print")+
"...",parentId:f,onclick:genericOnClick});mnuSelectedCopy=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_copy")+"...",parentId:f,onclick:genericOnClick});mnuSelectedEMail=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_email")+"...",parentId:f,onclick:genericOnClick});mnuSelectedExtEditor=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_external")+"...",parentId:f,onclick:genericOnClick});f=e||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_capture_browser")+
"..."});mnuBrowserEdit=e||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_edit")+"...",parentId:f,onclick:genericOnClick});mnuBrowserSave=e||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_save")+"...",parentId:f,onclick:genericOnClick});mnuBrowserSavePDF=e||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_save_pdf")+"...",parentId:f,onclick:genericOnClick});mnuBrowserSendOneNote=e||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_onenote")+
"...",parentId:f,onclick:genericOnClick});mnuBrowserUpload=e||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_upload")+"...",parentId:f,onclick:genericOnClick});mnuBrowserPrint=e||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_print")+"...",parentId:f,onclick:genericOnClick});mnuBrowserCopy=e||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_copy")+"...",parentId:f,onclick:genericOnClick});mnuBrowserEMail=e||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_email")+
"...",parentId:f,onclick:genericOnClick});mnuBrowserExtEditor=e||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_external")+"...",parentId:f,onclick:genericOnClick});f=e||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_capture_tabs")+"..."});mnuUnlockProFeatures=b||e||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_switch_pro_tabs"),parentId:f,onclick:genericOnClick});mnuAllTabsSinglePDF=e||chrome.contextMenus.create({enabled:b,title:chrome.i18n.getMessage("action_save_pdf_single")+
"...",parentId:f,onclick:genericOnClick});mnuAllTabsEdit=e||chrome.contextMenus.create({enabled:b,title:chrome.i18n.getMessage("action_edit")+"...",parentId:f,onclick:genericOnClick});mnuAllTabsSave=e||chrome.contextMenus.create({enabled:b,title:chrome.i18n.getMessage("action_save")+"...",parentId:f,onclick:genericOnClick});mnuAllTabsSendOneNote=e||chrome.contextMenus.create({enabled:b,title:chrome.i18n.getMessage("action_onenote")+"...",parentId:f,onclick:genericOnClick});mnuAllTabsUpload=e||chrome.contextMenus.create({enabled:b,
title:chrome.i18n.getMessage("action_upload")+"...",parentId:f,onclick:genericOnClick});mnuAllTabsPrint=e||chrome.contextMenus.create({enabled:b,title:chrome.i18n.getMessage("action_print")+"...",parentId:f,onclick:genericOnClick});mnuAllTabsClipboard=e||chrome.contextMenus.create({enabled:b,title:chrome.i18n.getMessage("action_copy")+"...",parentId:f,onclick:genericOnClick});mnuAllTabsEMail=e||chrome.contextMenus.create({enabled:b,title:chrome.i18n.getMessage("action_email")+"...",parentId:f,onclick:genericOnClick});
mnuAllTabsExtEditor=e||chrome.contextMenus.create({enabled:b,title:chrome.i18n.getMessage("action_external")+"...",parentId:f,onclick:genericOnClick});a();!e&&b&&(resumeMenuEnabled&&(mnuResume=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_resume")+"...",onclick:genericOnClick})),mnuOpenFile=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_open_file")+"...",onclick:genericOnClick}),mnuOpenClipboard=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_open_clipboard")+
"...",onclick:genericOnClick}),a());mnuPreferences=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_options")+"...",onclick:genericOnClick});mnuFireShotNative=!isWindows()||!e||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_install_native")+"...",parentId:f,onclick:genericOnClick});e||a()}e||!b||c||(mnuRegister=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_register")+"...",onclick:genericOnClick}),mnuEnterLicense=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_enter_license")+
"...",onclick:genericOnClick}));e||b||(mnuUpgrade=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_switch_pro")+"!",onclick:genericOnClick}));mnuViewDemo=e||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_view_demo"),onclick:genericOnClick});mnuSupport=e||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_support"),onclick:genericOnClick});!e&&b&&c&&(mnuLicensingInfo=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_license_info"),onclick:genericOnClick}));
mnuAbout=e||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_about"),onclick:genericOnClick})}updateLastActionInContextMenu();fEntered=!1}}}))}function restoreBadge(){getOption(cQueuedBadgeURLPref)&&"undefined"!==getOption(cQueuedBadgeURLPref)&&showBadge(getOption(cQueuedBadgeURLPref))}
function executeGrabber(a,b,c,e,h,f){f=f||0;guiItemsLocked||(h||setLastActionAndMode(a,b),b===cModeTabs?captureTabs(a):(multiPDFMode&&(pluginCommand("cancelMultiPagePDF"),multiPDFMode=void 0),chrome.tabs.query({currentWindow:!0,active:!0},function(d){0<d.length&&capturePage(a,b,c,e,d[0],f)})))}
function captureTabs(a){function b(f,d){return{next:function(k){d(k)||f(this)}}}var c=new function(){return{running:!1,start:function(){var f=0,d=["images/progress_1.png","images/progress_2.png","images/progress_3.png","images/progress_4.png"],k=this,g=function(){k.running?(chrome.browserAction.setIcon({path:d[++f%4]}),setTimeout(function(){g()},500)):k.defaultIcon()};this.running=!0;g()},stop:function(){this.running=!1;this.defaultIcon()},defaultIcon:function(){chrome.browserAction.setIcon({path:"images/sss_19.png"})}}};
c.start();var e=a===cActionMultiPDF?a:cActionSilentAdd,h=-1;a===cActionMultiPDF&&(pluginCommand("startMultiPagePDF"),multiPDFMode=!0);(function(f){return new Promise(function(d){var k=0;chrome.tabs.query({currentWindow:!0},function(g){if(g&&0!==g.length){for(var l=0;l<g.length&&-1===h;++l)g[l].active&&(h=l);var m=0;(new b(function(q){try{chrome.tabs.highlight({windowId:g[m].windowId,tabs:m},function(){checkTabReadyForCapturing(g[m].id,5E3,function(n){n?capturePage(f,cModeEntire,void 0,function(p){p&&
++k;q.next()},g[m++],0):(m++,q.next())})})}catch(n){logError(n.message),d(k)}},function(){return m>=g.length?(d(k),!0):!1})).next()}else d(k)})})})(e).then(function(f){c.stop();a===cActionMultiPDF?(pluginCommand("endMultiPagePDF"),multiPDFMode=void 0):pluginCommand("doGroupAction",{action:a,count:f});0<=h&&chrome.tabs.highlight({tabs:h})})}
function initHandlers(){chrome.tabs.onUpdated.addListener(function(a,b,c){b&&"complete"===b.status&&(/https:\/\/getfireshot(\.com)?\/activate\.php/.test(c.url)||!isCustomBuild()&&!isAPIEnabled()||initAPI("pageLoad"),fInjectGmailScript&&/^https?:\/\/mail.google.com\/mail.*$/.test(c.url)&&(getConsolePtr()("Executing script for: "+c.url),chrome.tabs.executeScript(a,{file:"scripts/3p/inboxsdk.js",runAt:"document_end"},function(){chrome.runtime.lastError&&getConsolePtr()("error:"+chrome.runtime.lastError);
chrome.tabs.executeScript(a,{file:"scripts/fsGmail.js",runAt:"document_end"},function(){chrome.runtime.lastError&&getConsolePtr()("error:"+chrome.runtime.lastError);fInjectGmailScript=!1})})))});chrome.tabs.onActivated.addListener(function(a){(isCustomBuild()||isAPIEnabled())&&initAPI("tabSwitch")});chrome.commands.onCommand.addListener(function(a){getConsolePtr()("Command:",a);"last-used-action"===a&&(fCapturing||shortcutProcessing?fCapturing&&stopCapturing():captureLastUsedMode())})}
function init(){initMessaging();initHandlers();isSafari()&&setOption(cSafariFirstSavePref,"true");document.addEventListener("DOMContentLoaded",function(){restoreBadge();getVersionInfo();updateContextMenu();checkAdvancedUpdates()})}init();
